name: Deploy-Web-Forms

on:
  push:
    branches: ["staging", "main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20.x"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::691071635361:role/github-actions-oidc-role
          aws-region: us-east-1

      - name: Install Pulumi
        uses: pulumi/actions@v5
        with:
          pulumi-version: 3.117.0
      - name: Install dependencies
        run: npm ci

      - name: Build CLI scripts
        run: npx tsc -p tsconfig.cli.json
      - name: Prepare Form Data
        env:
          SERVICE_DESK_USERNAME: ${{ secrets.SERVICE_DESK_USERNAME }}
          SERVICE_DESK_API_KEY: ${{ secrets.SERVICE_DESK_API_KEY }}
        run: node dist/setup_form_data.js --path config/formConfig.json --outPath form_data.json

      - name: Create .env file from secrets
        run: |
          cat <<EOF > .env
          VERIFICATION_FROM_EMAIL_ADDR=${{ secrets.VERIFICATION_FROM_EMAIL_ADDR }}
          SERVICE_DESK_USERNAME=${{ secrets.SERVICE_DESK_USERNAME }}
          SERVICE_DESK_API_KEY=${{ secrets.SERVICE_DESK_API_KEY }}
          SERVICE_DESK_DOMAIN=${{ secrets.SERVICE_DESK_DOMAIN }}
          FRIENDLY_CAPTCHA_API_KEY=${{ secrets.FRIENDLY_CAPTCHA_API_KEY }}
          FRIENDLY_CAPTCHA_SITEKEY=${{ secrets.FRIENDLY_CAPTCHA_SITEKEY }}
          EOF

      - name: Deploy SST
        run: |
          STAGE=${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}
          npx sst deploy --stage $STAGE
